---
title: "Polads Replication"
author: "Dominique Lockett"
date: '2023-01-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(cowplot)
library(descr)
library(readr)
library(magick)
library(dplyr)
library(ggeffects)
library(magrittr)
library(grid)
library(kableExtra)
library(stringr)
library(gridExtra)
library(knitr)
library(ggplot2)
library(gtable)
library(labelled)
library(haven)
library(gmodels)
library(png)
library(tidyverse)
library(cjoint)
library(stargazer)
library(Hmisc)
library(sjPlot)
library(labelled)
library(haven)
library(png)
library(magicfor)    
library(magicfor)  
library(fastDummies)
library(lme4)
library(coefplot)
library(pBrackets)
library(estimatr)
library(ggtext)
library(texreg)
local <- 'C:/Users/Path/to/Data/PolAdsTransparency/politics_user_study/'
####################
#data, models 
#and functions 
#for tables and plots
######################
#customized cjoint plot func
source(paste0(local,'plot_amce.R'))#to extract cjoint data for plots, I modify their source code
tass1 <- read.csv(paste0(local,'Data/TASS 04/8557_WUSTL-Weidenbaum04_MAIN.csv'))
#regulation opinions
tass2 <- read.csv(paste0(local,'Data/TASS 05/8557_WUSTL-Weidenbaum05_Redacted.csv'))

#conjoint
cj <- read.csv(file = paste0(local,'data/Conjoint/CJ.csv'), header = TRUE,
               stringsAsFactors = T)

follow <- read.csv(paste0(local,'Data/Follow up/polad.csv'))

#real ads means
dat <- read.csv(paste0(local,'data/Real', '/data.csv'))
datb <- read.csv(paste0(local,'data/Real', '/datb.csv'))
datc <- read.csv(paste0(local,'data/Real', '/datc.csv'))

#real ads lm
pooled    <- read.csv(paste0(local,'data/Real','/pooled.csv'))



####################
#Functions objects 
#and transformations
#for plots tables
#and models
####################

####################
#global custom theme

label.baseline = TRUE
text.size = 30
text.color = "black"
point.size = 0.5
dodge.size = 0.9
font.family=NULL
theme_bw1 <- function(base_size = text.size, base_family = "") {
  theme_bw(base_size = base_size, base_family = base_family 
  ) %+replace% 
    theme(axis.text.x = 
            element_text(size = base_size *  0.9, 
                         colour = text.color, hjust = 0.5,
                         vjust = 1),  
          axis.text.y = element_text(size = base_size, 
                                     colour = text.color,
                                     hjust = 0, vjust = 0.5,
                                     family = font.family), 
          axis.title.y = element_text(size = base_size, 
                                      angle = 180, vjust = 0.01,
                                      hjust = 0.1, 
                                      family = font.family), 
          
          plot.title = element_text(face = "bold", 
                                    family = font.family),
          axis.ticks = element_blank(), 
          
          legend.background = element_blank(), 
          
          legend.key = element_blank(),
          panel.background = element_blank(), 
          panel.border = element_blank(), 
          strip.background = element_blank(), 
          
          
          plot.background = element_blank(), complete = TRUE,
          panel.grid.minor =   element_blank(),
          panel.grid.major =  element_line(colour = "grey87",size=0.5))
}
theme_set(theme_bw1())



##############
#export tables

#small function that exports tables to .tex file [lm-robust]
mod_texreg <- function(output.file, ...) {
  output <- capture.output(texreg(...))
  cat(paste(output, collapse = "\n"), "\n", file=output.file, append=F)
}




###########
#regulation opinion

#PID recode
tass2$pid <- NA 
tass2$pid[tass2$PartyID7 == -1 ] = NA
tass2$pid[tass2$PartyID7 == 4 ] = "Moderate/Independent/None"
tass2$pid[tass2$PartyID7 < 4 & tass2$PartyID7 > 0] = "Democrat"
tass2$pid[tass2$PartyID7 > 4 & tass2$PartyID7  < 8] = "Republican"

#WEIGHTED MEANS + CIS-function to extract wtd CIs
wtd.ci <- function(x, weights, conf.level = 0.95) {
  require(Hmisc)
  nx <- length(x)
  df <- nx - 1
  vx <- wtd.var(x, weights, normwt = TRUE) ## From Hmisc
  mx <- weighted.mean(x, weights, na.rm=T)
  stderr <- sqrt(vx/nx)
  tstat <- mx/stderr ## not mx - mu
  alpha <- 1 - conf.level
  cint <- qt(1 - alpha/2, df)
  cint <- tstat + c(-cint, cint)
  CI <- c(cint * stderr)
  c( Estimate=mx,"CI lower"=CI[1],"CI upper"=CI[2],"Std. Error"=stderr)
}


# which(colnames(tass2)=='ADS4_A')
# which(colnames(tass2)=='ADS4_T')
# 
#ADS4_A:T -> 137:156
#opinion survey questions of interest
Ads3 <- 137:156


#recode opinion survey 
for(i in 1:20){
  tass2[,Ads3[i]] <- to_factor(tass2[,Ads3[i]])
  tass2[,Ads3[i]]<- recode(tass2[,Ads3[i]], "1" = "Strongly agree",
                           "2" = "Agree", "3" = "Agree only a little", 
                           "4" = "Disagree only a little", '5' = 'Disagree',
                           '6' = 'Strongly disagree',"77" = NA_character_, 
                           "98" = NA_character_, "99" = NA_character_) 
  
}

#opinion questions from original survey
topics3 <-c("Political ads should be removed if they contain false information",
            "Political ads should be allowed, even if they contain misleading information",
            "Political ads with false content should be allowed, but labeled with a
 warning","Companies should not try to label political ads as false, even if they
 containing misleading information","No political ads should be allowed at all",
            "Political candidates should always be allowed to post ads without restriction",
            "All ads on controversial topics should be removed, regardless of source","Ads
 that encourage voting should always be permitted","Ads from news organizations
 should be exempted from regulations of political advertising","Political ads from 
 news organizations should be subject to the same regulations as ads from other sources",
            "Ads that discredit voting by mail should not be permitted on social media",
            "Political ads should include information about who paid for them","Political
 advertisers should not be required to disclose their funding sources","Microtargeting
 political ads to specific audiences based on things like age, gender, and race should
 not be permitted.","Political advertisers should be allowed to select who sees their
 ads","Ads that contain misinformation about a candidate should be removed","All ads
 about candidates should be allowed, even if they contain false content","Companies
 should provide a publicly accessible database of all political ads","Ads about
 candidates or upcoming elections should be banned, but ads about social issues (e.g.,
 guns or abortion) should still be allowed","Ads from certain sources like political
 action committees (PACs) and dark money organizations should be banned")

nq<- c('Ads encouraging voting allowed',
                       'No political ads', 
                       'All controversial ads banned', 
                       'Candidate ads banned but issue ads allowed',
                       'PACs/dark money ads banned',
                       'Political advertisers funding sources private',
                       'Political advertisers funding sources displayed on ad ',
                       "Public database for companies' political ads",   
                       'Microtargeting political ads banned',
                       'Advertisers choose who sees',
                       'News orgs exempt from political ad regulations ',
                       "News orgs' political ads regulated" )


###
#CJ
#Define baselines
#cjoint needs baselines defined separately for unconditional and interacted
baselines <- list()
baselines$sourceType <- "Company"
baselines$sourceOrient <- "Pro-environment"
baselines$messageStrength <- "Weak"
baselines$messageOrient <- "Pro-environment"
baselines$image <- "Landscape"
baselines$pid <- 'Republican'

bases <- list()
bases$image <- 'Landscape'
bases$messageOrient <- 'Pro-environment'
bases$messageStrength <- 'Weak'
bases$sourceOrient <- 'Pro-environment'
bases$sourceType <- 'Company'





####################
#data, models 
#and functions 
#for tables and plots
######################
#customized cjoint plot func
source(paste0(local,'plot_amce.R'))#to extract cjoint data for plots, I modify their source code
tass1 <- read.csv(paste0(local,'Data/TASS 04/8557_WUSTL-Weidenbaum04_MAIN.csv'))
#regulation opinions
tass2 <- read.csv(paste0(local,'Data/TASS 05/8557_WUSTL-Weidenbaum05_Redacted.csv'))

#conjoint
cj <- read.csv(file = paste0(local,'data/Conjoint/CJ.csv'), header = TRUE,
               stringsAsFactors = T)
#real ads means
datd <- read.csv(paste0(local,'data/Real', '/datc.csv'))

#real ads lm
pooled     <- read.csv(paste0(local,'data/Real','/pooled.csv'))
orig <- read.csv(paste0(local,'data/Real', '/original.csv'))
redo <- read.csv(paste0(local,'data/Real', '/correction.csv'))

#follow up
follow <- read.csv(paste0(local,'Data/Follow up/polad.csv'))
follow$political_affiliat[follow$political_affiliat==""] <-NA
follow$political_affiliat[follow$political_affiliat=="Other:"] <-"Independent"
follow$political_affiliat = factor(follow$political_affiliat, levels=(c("Strong Democrat","Weak Democrat","Independent","Weak Republican","Strong Republican")))

ads2 <- follow[,c(33,30,27,29,42,43,36,37,34,35,40,41,31,32,38,39)]


```

## Opinions Survey
### Table 3

```{r t3}

sub <- c(144,141,143,155,156,149,148,154,150,151,145,146)#column numbers, custom order
new <- data.frame(matrix(nrow=12, ncol=4))#storage object
colnames(new)<-c('est','upper','lower','std. err')#grabbing means and cis
#neat names for plots order the same as _sub_ ordering

#scale <- c('Strongly \n agree','Agree','Agree\n a little','Disagree\n a little','Disagree', 'Strongly \n disagree')#x-axis names


for(i in 1:length(sub)){#go through each column
  #weighted cis Real Ad opinions with frequency and percentages
  new[i,] <- wtd.ci(as.numeric(as.factor(tass2[,sub[i]])), weights=tass2$WEIGHT)
}

new['question'] <- nq
new$question <- factor(new$question, levels= rev(new$question))#forced factoring so its not alphabetical
colnames(new) <- c('Mean','Lower 95% CI','Upper 95% CI','Standard Err.', 'Question')

new
```

### Table 4

```{r t4, echo=FALSE}
```

## 
### Figure 1

```{r f3, echo=FALSE}



ads <- follow[,c(18,19,20,22,23,24)]

for(i in 1:ncol(ads)){
  for(j in  1:nrow(ads)){
    ads[j,i][ads[j,i]==""] <- NA}
  ads[,i] <- factor(ads[,i], levels=(c("Not at all political","Slightly political","Somewhat political","Very political","Extremely political")))
}


vals <- data.frame(matrix(ncol=4,nrow=6,NA))
colnames(vals) <- c('Estimate','Lower 95 CI','Upper 95 CI','Standard Err.')

for(i in 1:ncol(ads)){
  vals[i,] <- ci(as.numeric(ads[,i]), na.rm=T)
}

vals$Ad <- c( "Strong pro-development","Strong pro-environment", "Moderate pro-development","Moderate pro-environment", "Weak pro-development", "Weak pro-environment"  )
vals$Ad = factor(vals$Ad, levels=rev( c( "Strong pro-development","Strong pro-environment", "Moderate pro-development","Moderate pro-environment", "Weak pro-development", "Weak pro-environment"  )))
conjoint <- vals
#plots
f1<- ggplot(vals, aes(y = Estimate, x = Ad  ))+
  geom_pointrange(aes(y = Estimate,ymin = `Lower 95 CI`, 
                      ymax = `Upper 95 CI`),
                  size = 1, color = "sienna4") +
  coord_flip() + 
  ylim(1,4)+  xlab("")+ 
  ylab("")+ 
  scale_y_continuous(limits = c(1,5),
                     labels=c('Not \n political \n (1)',
                              '',
                              '\n\n (3)',
                              '',
                              'Extremely \n political \n (5)'))+ 
  theme(panel.spacing.x = unit(27, "mm"),
        axis.text.x=element_text(angle=0,
                                 hjust=0.5,vjust=.5))#+
# theme(axis.text.y = element_text(face=rev(c("bold","bold",
#                                             "italic","italic",
#                                             'plain','plain','plain','plain'))))

f1+theme(text=element_text(size=20)) + scale_color_manual(values =  c("sienna4", 'navajowhite3'), name = "")+ geom_hline( yintercept = 0, colour = "gray", size = 1, lty= 'dashed')+
  theme(plot.margin = unit(c(1,1,2,3), "cm"))+
  theme(axis.text.y= element_text( size = 20),axis.text.x= element_text( size = 18),legend.text=element_text(size=20))

```
# Conjoint analysis
## Unconditional model

### Table 5

```{r t5, echo=FALSE}
unconditional <- amce(dv1 ~ image  + messageOrient + messageStrength + sourceOrient + sourceType  , respondent.id= 'CaseId', cluster=TRUE,  weights ='WEIGHT', data=cj, baseline= baselines, na.ignore=T)
summary(unconditional)

```

### Figure 4

```{r f4, echo=FALSE}

nums <<- 7:20
plt1(unconditional)


plt1(unconditional, 
     colors=c("paleturquoise4","lightpink3","sienna4", 'navajowhite3'),
     xlab="Change in \n Pr(Ad considered more political)", 
     attribute.names= c('Images','Message orientation',
                        'Message strength','Source orientation',
                        'Source type'),
     point.size=1.5, 
     plot.theme=theme_set(theme_bw1())+
       theme(axis.text.y = element_text(size=rev(c(30,24 ,30 , 30, 24, 30 ,30,30 ,24,30,30, 24, 30, 30))))+
       theme(axis.text.y = element_text(face=rev(
         c("bold","italic", "plain","bold", 'italic',
           'plain','plain','bold', "italic","plain",
           'bold','italic','plain','plain'))))+
       theme(axis.text.x = element_text(size=24))+
       theme(legend.position = 'none'))


#save
ggsave(paste0(local,"Publishing materials/Replication plots/","cj-uncondition-plot.pdf"), width = 12, height = 9, units = "in")

```



# Real advertisements experiment

## Source
### Table 6

```{r t6, echo = FALSE}

sourcexpriorxmess <- amce(dv1 ~   image  + messageOrient + messageStrength + sourceOrient + sourceType  + priors +  messageOrient*priors + sourceOrient*priors, cluster=TRUE, respondent.id="CaseId", weights ='WEIGHT', data=cj, baseline= baselines, respondent.varying= 'priors', na.ignore=T)

summary(sourcexpriorxmess)


```

```{r f5, echo=FALSE}


#source and message interaction:
#Fig. 2

plt1(sourcexpriorxmess,plot.display='interaction',colors=c("paleturquoise4","lightpink3","sienna4", 'navajowhite3'))

d <- plotdata
d$group[d$group == "<NA>"] <- NA
d$facet <- factor(d$facet,levels=unique(d$facet))
d$var <- factor(d$var, levels=c(levels(d$var)[4:6],levels(d$var)[1:3]))
d$prior[d$facet=="Conditional on\npriors = Pro-development"]<- 'Pro-development'
d$prior[d$facet==levels(d$facet)[2]]<- 'Pro-environment'
d$`Prior attitudes:` <- d$prior

group.order=c('messageOrient','sourceOrient')
if (!is.null(group.order)){
  
  n.row <- length(unique(as.character(d$var)))
  order.var <- vector("character", length = n.row)
  
  i <- 1
  while (i<n.row){
    for (j in group.order){
      order.var[i] <- unique(as.character(d$var[d$var==gsub(" ","",j)]))
      i <- i+1
      temp.d <- d
      temp.d$group <- gsub(" ","",temp.d$group)
      temp.d <- subset(temp.d, group==gsub(" ","",j))
      
      temp.var <- unique((as.character(temp.d$var)))
      order.var[i:(i+length(temp.var)-1)] <- temp.var
      i <- i+length(temp.var)
    }
  }
  order.var <- rev(order.var)
  
  order.df <- data.frame(order.var, 1:length(order.var))
  colnames(order.df) <- c("var", "order")
  
  d$var <- factor(d$var, levels=order.var)
  
  d <- merge(d, order.df, by.x="var", by.y="var", suffixes=c("",""))
  
}


labels= c('Message orientation:','  (Baseline: Pro-environment) ','  Pro-development ','Source orientation:','  (Baseline: Pro-environment)', '  Pro-development')
col <-c("paleturquoise4","lightpink3")


f5=ggplot(d, aes(y = pe, x = var, color = `Prior attitudes:`, shape=`Prior attitudes:`))+
  theme_set(theme_bw1())+
  geom_hline(yintercept = 0, size = 1, colour = "gray", 
                   linetype = "dashed") +
  geom_pointrange(aes(y=pe,ymin = lower, ymax = upper, color = `Prior attitudes:`, shape=`Prior attitudes:`), 
                  position=position_dodge(width = -.8),
                  size = 1.5)+
  xlab("")+
  ylab('Change in \n Pr(Ad considered more political)')+
  ylim(-.13,.13)+
  coord_flip()


f5 +scale_x_discrete(labels=rev(labels))+
  theme(axis.text.y = element_text(face=rev(c("bold","italic", "plain","bold", 'italic','plain'))))+  
  theme(axis.text.y = element_text(size=rev(c(30,24 ,30 , 30, 24, 30))))+
  theme(legend.position = 'bottom',legend.justification = "left")+
  scale_color_manual(values=c("paleturquoise4","lightpink3"), 
                    guide="legend")+
  theme(axis.text.x= element_text( size = 20),legend.text=element_text(size=20))+
  theme(axis.title.x = element_text(size=24))+
  theme(legend.title = element_text(size=22, face = 'bold'))+
  theme(plot.margin = margin(1,2,0,0, "cm"))
f5
```


```{r f6, echo =FALSE}




#plots



for(i in 1:ncol(ads2)){
  for(j in  1:nrow(ads2)){
    ads2[j,i][ads2[j,i]==""] <- NA}
  ads2[,i] <- factor(ads2[,i], levels=(c("Not at all political","Slightly political","Somewhat political","Very political","Extremely political")))
}

weights <-data.frame(matrix(ncol=4,nrow=16,NA))
colnames(weights) <- c('Estimate','Lower 95 CI','Upper 95 CI','Standard Err.')

for(i in 1:ncol(ads2)){
  weights[i,] <- ci(as.numeric(ads2[,i]), na.rm=T)
}

weights$`Political Content` <- rep(c('Strong','Weak'),8)
weights$Ad <- rep(c("Biden","Trump","Power", "Sierra","MSC",
                    'Patagonia',"Exxon","Colgate"),each =2)
weights$Ad = factor(weights$Ad, levels=rev(c("Biden","Trump","Power", "Sierra",'Patagonia',"MSC","Exxon","Colgate")))

realAds <- weights

f6 <- ggplot(weights, aes(y = Estimate, x = Ad, colour= `Political Content`   ))+
  geom_pointrange(aes(y = Estimate,ymin = `Lower 95 CI`, 
                      ymax = `Upper 95 CI`),
                  size = 1) +
  coord_flip() + 
  ylim(1,4)+  xlab("")+ 
  ylab("")+ 
  scale_y_continuous(limits = c(1,5),
                     labels=c('Not \n political \n (1)',
                              '',
                              ' \n\n (3)',
                              '',
                              'Extremely \n political \n (5)'))+ 
  theme(panel.spacing.x = unit(27, "mm"),
        axis.text.x=element_text(angle=0,
                                 hjust=0.5,vjust=.5))+
  theme(axis.text.y = element_text(face=rev(c("bold","bold",
                                              "italic","italic",
                                              'plain','plain','plain','plain'))))

f6+theme(text=element_text(size=20)) + scale_color_manual(values =  c("sienna4", 'navajowhite3'), name = "")+ geom_hline( yintercept = 0, colour = "gray", size = 1, lty= 'dashed')+
  theme(plot.margin = unit(c(1,1,2,3), "cm"))+
  theme(axis.text.y= element_text( size = 20),axis.text.x= element_text( size = 18),legend.text=element_text(size=20))




```


## Table 7

```{r t7, echo=FALSE}

trump <- lm_robust(estimate ~ Trump, data =subset(pooled,pooled$experiment=='POLADSTRUMP1S4'|pooled$experiment == 'POLADSTRUMP2S4') , weights = WEIGHT ,cluster=CaseId)


biden$estimate <- ifelse(biden$estimate <3, 0 ,1)
biden  <- lm_robust(estimate ~ Biden, data = subset(pooled,pooled$experiment=='POLADSBIDEN1S4'|pooled$experiment == 'POLADSBIDEN2S4'), weights = WEIGHT )

patagonia  <- lm_robust(estimate ~ Patagonia, data =subset(pooled,pooled$experiment=='POLADSPATAGONIA1S4'|pooled$experiment == 'POLADSPATAGONIA2S4'), weights = WEIGHT )

exxon <- lm_robust(estimate ~ Exxon, data = subset(pooled,pooled$experiment=='POLADSEXXON1S4'|pooled$experiment == 'POLADSEXXON2S4'), weights = WEIGHT )

power  <- lm_robust(estimate ~ Power, data = subset(pooled,pooled$experiment=='POLADSPOWER1S4'|pooled$experiment == 'POLADSPOWER2S4'), weights = WEIGHT )


sierra <- lm_robust(estimate ~Sierra, data = subset(pooled,pooled$experiment=='POLADSSIERRA1S4'|pooled$experiment == 'POLADSSIERRA2S4'), weights = WEIGHT )


colgate <- lm_robust(estimate ~ Colgate, data = subset(pooled,pooled$experiment=='POLADSCOLGATE1S4'|pooled$experiment == 'POLADSCOLGATE2S4'), weights = WEIGHT )


msc <- lm_robust(estimate ~ MSC, data = subset(pooled,pooled$experiment=='POLADSMSC1S4'|pooled$experiment == 'POLADSMSC2S4'), weights = WEIGHT )


```

### Figure 7


```{r f7, echo=FALSE}



#reorder level for display
datd$Ad = factor(datc$Ad, levels=rev(c("Biden","Trump","Power", "Sierra",
                                       'Patagonia',"Exxon","MSC","Colgate")))
datd$`Political Content` <- datc$political

#plots
f7 <- ggplot(datd, aes(y = Estimate, x = Ad , color=`Political Content`  ))+
  geom_pointrange(aes(y = Estimate,ymin = `Lower.CI`, 
                      ymax = `Upper.CI`),
                  position = position_dodge(width = -.6),
                  size = 1) +
  coord_flip() + 
  ylab("")+ xlab("")+
  ylim(1,5)
   theme(panel.spacing.x = unit(27, "mm"),
        axis.text.x=element_text(angle=0,
                                 hjust=0.5,vjust=.5))+
  theme(axis.text.y = element_text(face=rev(c("bold","bold",
                                              "italic","italic",
                                              'plain','plain','plain','plain'))))

f7+theme(text=element_text(size=20)) + scale_color_manual(values =  c("sienna4", 'navajowhite3'), name = "")+
  theme(plot.margin = unit(c(1,1,2,3), "cm"))+
  theme(axis.text.y= element_text( size = 20),axis.text.x= element_text( size = 18),legend.text=element_text(size=20))
```

```{r t8, echo =F}



```


```{r t9, echo =F}


```






