---
output: pdf_document
classoption: landscape
header-includes:
  \usepackage{subcaption}
  \usepackage{booktabs}
  \usepackage{caption}
---
# 2. Real Ads Experiment
## Balance Checks
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F)
library(ggplot2)
library(gmodels)
library(Hmisc)
library(sjPlot)
library(knitr)
library(viridis)
library(survey)

library(magicfor)    
library(tidyverse)# load library
library(kableExtra)
polAdORIG <- read.csv('C:/Users/dl0ck/OneDrive/Summer 2021/PolAdsTransparency/politics_user_study/Data/TASS 04/8557_WUSTL-Weidenbaum04_MAIN.csv') 

polAdREDO <- read.csv('C:/Users/dl0ck/OneDrive/Summer 2021/PolAdsTransparency/politics_user_study/Data/TASS04Reask/8557_WUSTL-Weidenbaum04Reask.csv') 

adrow <-c('Trump','Biden','Exxon',
          'Patagonia','Power',
          'Sierra','Colgate', 'SMSC')
```

```{r weighted-mean}
wtd.ci <- function(x, weights, conf.level = 0.95) {
  require(Hmisc)
  nx <- length(x)
  df <- nx - 1
  vx <- wtd.var(x, weights, normwt = TRUE) ## From Hmisc
  mx <- weighted.mean(x, weights, na.rm=T)
  stderr <- sqrt(vx/nx)
  tstat <- mx/stderr ## not mx - mu
  alpha <- 1 - conf.level
  cint <- qt(1 - alpha/2, df)
  cint <- tstat + c(-cint, cint)
  CI <- c(cint * stderr)
  c( Estimate=mx,"CI lower"=CI[1],"CI upper"=CI[2],"Std. Error"=stderr)

}


```

```{r Randomization-check, results='asis'}
#Checking randomization and balance of variables against basic demographic variables
magic_for(silent = TRUE)

polAd <- list()

polAd[[1]] <- polAdORIG
polAd[[2]] <- polAdREDO

for(d in 1:2){
  #tables:
  n <- 0
  x <- which(colnames(polAd[[d]])=='POLADSTRUMP1S4')-2#+2 to column 239 which is trump1
  random <- c()
  for(i in 1:8){
    
    x <- x+2#every other colname to indicate which picture
    n <- n+1 #index for rownames
    random <- rbind(random,table(polAd[[d]][,which(colnames(polAd[[d]])=='RND_00')+i]))#columns 23:30 = RND_01:08
    rownames(random)[n] <- adrow[n]
  }
  colnames(random)<-c('0','1')
put(random)}
t1a <-  kbl(magic_result()$random[[1]], format = "latex", booktabs = TRUE,linesep = c("", "", "", ""))
t2a <-  kable( magic_result()$random[[2]], format = "latex", booktabs = TRUE,linesep = c("", "", "", ""))

```

```{r Randomization-check-display, results='asis'}

  
cat(c("\\begin{table}[H]\\vspace{10em}
  \\caption{Randomization balance}
    \\begin{minipage}{.6\\textwidth}
      \\subcaption{Original}
      \\centering",
        t1a,
    "\\end{minipage}%
    \\begin{minipage}{.1\\textwidth}
      \\centering
       \\subcaption{Correction}",
        t2a,
    "\\end{minipage} 
\\end{table}"
))  

```




```{r balance-check-long, results='asis'}
magic_free()
magic_for(silent = TRUE)

columns <- cbind( c('AGE','GENDER','P_PARTYID7','IDEO1S4') , c('AGE','GENDER','PartyID7','IDEO1S4') )

for(d in 1:2){
  #balance:
  n <- 0
  x <- which(colnames(polAd[[d]])=='POLADSTRUMP1S4')-2#+2  trump1
  tabs <- c()
  demo <- columns[,d] #colnames of demos I want
  for(i in 1:8){
    x <- x+2#every other column for image indicator
    for(j in 1:4){
      n <- n+1#index for tabs rownames
      dem <- polAd[[d]][,which( colnames(polAd[[d]])==demo[j])] #grab the index of the
      #specific demographic variable I wanat
      rnd <- polAd[[d]][,which(colnames(polAd[[d]])=='RND_00')+i] #colnames associated with RND_0X
      tabs <- rbind(tabs,cbind(summary(dem[rnd==0],na.rm=T)[4],
                               summary(dem[rnd==1],na.rm=T)[4]))
      #4 rows for each of the demographics and 2 columns for the mean
      #when RND_0X == 1 or 0

      rownames(tabs)[n] <-paste(rep(adrow,each =4)[n],
                                 ":",capitalize(tolower(demo[j])))
    }
  }
  colnames(tabs)<- c('RND = 0','RND = 1')
  
  put(tabs)

}

t1b <- kable( magic_result()$tabs[[1]], format = "latex", booktabs = TRUE, linesep = c("", "", "", "\\addlinespace"))
t2b <-  kable( magic_result()$tabs[[2]], format = "latex", booktabs = TRUE, linesep = c("", "", "", '\\addlinespace'))
```

```{r balance-check-display, results='asis'}

  
cat(c("\\begin{table}[H]
  \\caption{Balance of randomization by image and demographic}
    \\begin{minipage}{.5\\textwidth}
      \\subcaption{Original}
      \\centering",
        t1b,
    "\\end{minipage}%
    \\begin{minipage}{.5\\textwidth}
      \\centering
        \\subcaption{Correction}",
        t2b,
    "\\end{minipage} 
\\end{table}"
))  

```


```{r recod-for-plot, include=FALSE}

#Data is reordered so that higher values mean more political and skipped/refused/don't know changed to NA's
for(d in 1:2){
  range1 <- which(colnames(polAd[[d]])=='POLADSTRUMP1S4'):
              which(colnames(polAd[[d]])=='POLADSMSC2S4')
  for(i in range1){
    #flip rating order and switch skipped/refused/don't knows to NA
     polAd[[d]][,i][polAd[[d]][,i]>5] <<- NA
     polAd[[d]][,i] <<- 6-polAd[[d]][,i]
  }
}


```


## Weighted Real Ad Averages and CI's
```{r experiments,fig.width=12, fig.height=6,fig.cap="Averages and confidence intervals by image"}



politic <- c('Low Political','High Political')
iter <- c('Original','Correction')

adfacet <- c(1,1,1,1,2,2,2,2)
magic_for(silent=T)
temp <- c()

for(d in 1:2){#for each experiment
  temp <-c()#reset temp
  for(j in 1:2){#for each index set (1=low political 2=high political)
    index <- which(colnames(polAd[[d]])=='POLADSTRUMP1S4')-j
    #index starting at 1 or 2 less than variables of interest to collect every other
    for(i in 1:8){#for every ad image
      index <- index + 2 #cycle through sets of images 
      #i.e. index 239 is trump1 which is the first in the consecutive 16 images 
      #trmp1 trump2 biden1 biden2 etc. high pol, low pol, high pol, low pol etc.
      #index(= 239) - j(=1) -> index(= 238) + 2(= 240) = trmp2-- low political
      #index(= 239) - j(=2) -> index(= 237) + 2(= 239) = trmp1-- high political
      data <- cbind(as.data.frame(cbind(t(as.matrix((wtd.ci(polAd[[d]][,index],
               polAd[[d]]$WEIGHT )))))),'Iteration'=iter[d],'political'=politic[j], 'Ad'=adrow[i], 'face'=adfacet[i])
      #convert the confidence interval output to columns and ad indicator columns
      #based on index d1=original, d2=correction, index1:8=ad images
      temp <- rbind(temp,data)#grab statistics
    }
  }
  put(temp)#nice little grabber function to collect data from for loops
}


data1 <- rbind(magic_result()$temp[[1]],magic_result()$temp[[2]])#the two outer loops combined into one dataframe

#flip factor order for prefered display
data1$Iteration = factor(data1$Iteration, levels=c('Original','Correction'))

#define some aesthetically pleasing colors
vir <- rep(c("salmon4","bisque2"),8)
dat1 <- subset(data1, data1$face==1)
dat2 <- subset(data1, data1$face==2)
```

```{r experiments-p1,fig.width=12, fig.height=6,fig.cap="Averages and confidence intervals by image-- Trump, Biden, Exxon, Patagonia"}

p1 <- ggplot(dat1, aes(y = Estimate, x = Ad, shape= as.factor(political),color = as.factor(political)))+
     geom_pointrange(aes(y = Estimate,
                      ymin = `CI lower`,
                      ymax = `CI upper`, fill = as.factor(political)),
                      position = position_dodge(width = -.6),
                      size = .5, fill  =vir) +
                      facet_wrap(~Iteration)+
                      scale_shape_discrete(name="", label=c("High Political", "Low Political")) +
                      scale_color_manual(name="", label=c("High Political", "Low Political"),
                      values =vir) +
    guides(shape = guide_legend(override.aes = list(fill = c("aquamarine4","lightpink3"))))+
    coord_flip() + 
    ylim(1,4)+
    xlab("") + ylab("")+
    theme_bw()+ 
    scale_y_continuous(limits = c(1,5), labels=c('Not at all political','','3','','Extremely political'))+ 
    theme(panel.spacing.x = unit(27, "mm"),axis.text.x=element_text(angle=15, hjust=0.5, vjust=.5))+ theme(axis.text.x = element_text(size = 12),strip.text.x = element_text(size = 10),
    legend.text = element_text(size = 10),
    axis.text.y = element_text(size = 10))
p1

```

```{r experiments-p2,fig.width=12, fig.height=7,fig.cap="Averages and confidence intervals by image-- Patagonia, Power, Sierra, Colgate, SMSC"}

p2 <- ggplot(dat2, aes(y = Estimate, x = Ad, shape= as.factor(political),color = as.factor(political)))+
     geom_pointrange(aes(y = Estimate,
                      ymin = `CI lower`,
                      ymax = `CI upper`, fill = as.factor(political)),
                      position = position_dodge(width = -.6),
                      size = .5, fill  =vir) +
                      facet_wrap(~Iteration)+
                      scale_shape_discrete(name="", label=c("High Political", "Low Political")) +
                      scale_color_manual(name="", label=c("High Political", "Low Political"),
                      values =vir) +
    guides(shape = guide_legend(override.aes = list(fill = c("aquamarine4","lightpink3"))))+
    coord_flip() + 
    xlab("") + ylab("")+
    theme_bw()+ 
    scale_y_continuous(limits = c(1,5), labels=c('Not at all political','','3','','Extremely political'))+ 
    theme(panel.spacing.x = unit(27, "mm"),axis.text.x=element_text(angle=15, hjust=0.5, vjust=.5))+ theme(axis.text.x = element_text(size = 12),strip.text.x = element_text(size = 10),
    legend.text = element_text(size = 10),
    axis.text.y = element_text(size = 10))
p2

```
